inspection frames
zopefoundation/RestrictedPython pull request #255
Opened 2023-07-06 21:49 UTC by loechel

2023-07-06 22:04 UTC, loechel commented
Feedback welcome.

* potential more documentation necessary on what to check on new Python Versions
* Changelog Entry
* maybe move / rename the new test file

2023-07-07 05:39 UTC, icemac requested changes
Thank you for tackling this issue.

I have some suggestions, gathered by trying it out in a Python interpreter.
Changing the error message also requires changing the tests.

2023-07-07 05:39 UTC, icemac commented on docs/contributing/index.rst
> +* check the documentation for ``inspect`` <https://docs.python.org/3/library/inspect.html> and adjust the ``transformer.py:INSPECT_ATTRIBUTES`` list
```suggestion
* Check the documentation for `inspect  <https://docs.python.org/3/library/inspect.html>`_ and adjust the ``transformer.py:INSPECT_ATTRIBUTES`` list.
```

2023-07-07 05:39 UTC, icemac commented on src/RestrictedPython/transformer.py
> +    "tb_lineno",
```suggestion
    # "tb_lasti",  # just an int
    # "tb_lineno",  # just an int
```

2023-07-07 05:39 UTC, icemac commented on src/RestrictedPython/transformer.py
> +    "f_lineno",
```suggestion
    # "f_lasti",  # just an int
    # "f_lineno",  # just an int
```

2023-07-07 05:39 UTC, icemac commented on src/RestrictedPython/transformer.py
> +    "gi_running",
```suggestion
    # "gi_running", # just a bool
```

2023-07-07 05:39 UTC, icemac commented on src/RestrictedPython/transformer.py
> +    # generator
```suggestion
    # code
    "co_code",
    # generator
```

2023-07-07 05:39 UTC, icemac commented on src/RestrictedPython/transformer.py
> +    "cr_running",
```suggestion
    # "cr_running",  # just a bool
```

2023-07-07 05:39 UTC, icemac commented on src/RestrictedPython/transformer.py
> +                    name=node.attr,
```suggestion
                f'"{node.attr}" is a restricted name,'
                ' that is forbidden to access in RestrictedPython.'
```

2023-07-07 10:21 UTC, loechel commented
@icemac, thanks for your comments and improvements recommendations.
I will close this pull request, see mail and follow up there.

2023-07-07 10:21 UTC, closed without merging