allow `@` expressions
zopefoundation/RestrictedPython pull request #269
Opened 2024-02-09 17:54 UTC by rawwerks

this commit updates transformers.py to allow `@` expressions. would close https://github.com/zopefoundation/RestrictedPython/issues/268.

2024-02-12 16:22 UTC, icemac commented
Thank you for your pull request.
We are currently asserting that `@` is not supported.
Could you come up with a test asserting that the @-operator works?

2024-02-13 23:16 UTC, rawwerks commented
this is a bit above my pay-grade, so please accept my apologies if i am totally misunderstanding how the tests work. 

i'm trying to follow the examples of `test_functiondef.py`...what about something like this?

```
def test_RestrictingNodeTransformer__visit_MatMult__1():
    """It allows the `@` operator for matrix multiplication."""
    source_code = """
class MatMulSupport:
    def __matmul__(self, other):
        return "MatMul Operation Allowed"

def test_matmul():
    a = MatMulSupport()
    b = MatMulSupport()
    return a @ b

result = test_matmul()
"""
    result = compile_restricted_exec(source_code)
    assert result.errors == (funtionandef_err_msg)

```

(i'm so unsure of myself that i'm hoping to get feedback before updating the PR)

2024-02-13 23:40 UTC, rawwerks commented
ok wait, this is probably the better place to do it: https://github.com/zopefoundation/RestrictedPython/pull/269/commits/959ac23ee015ba2c4aad0f3e98d1cc502689e350

(maybe not the right way, but i think it should work)

2024-02-14 07:31 UTC, icemac commented
I think I understood the idea of the tests and I think I can get it working but first we need some general paperwork:

Thank you for your contribution.

According to the contributing policies of the zopefoundation organization you need to sign a contributor agreement before any non-trivial change can be merged. For details please consult the [Contributing guidelines for zopefoundation projects](https://github.com/zopefoundation/.github/blob/master/CONTRIBUTING.md).

2024-02-14 22:21 UTC, rawwerks commented
i'm reviewing the document. 

in the meantime, hopefully we can do this:

this pull request (https://github.com/zopefoundation/RestrictedPython/pull/269) by Raymond Weitekamp (rawwerks) is marked with [CC0 1.0 Universal](http://creativecommons.org/publicdomain/zero/1.0?ref=chooser-v1).

2024-02-15 19:38 UTC, loechel requested changes
Please fix the linting errors and get the test green.

`transformer.py` Line 55-64 must be ammended and ``__matmul__`` be added, or the tests won't pass.

I would suggest to change the test to the more common used structure, where the source_code definition is definied before the test-case.

Thanks for the Pull request.

2024-02-15 19:38 UTC, loechel commented on tests/transformer/operators/test_arithmetic_operators.py
> +    # Assuming restricted_eval can execute the source_code and return the value of 'result'
As it is a test in RestrictedPython itself, this comment does not make sense. Whether the test passes and the result is 42 or not, there should not be any assumption.

2024-02-15 19:38 UTC, loechel commented on tests/transformer/operators/test_arithmetic_operators.py
> +class Vector:
The test-runner requires it to be:

```python
    source_code = """\
class Vector:
```

2024-02-19 07:27 UTC, icemac commented
@rawwerks Thank you for putting your changes into public domain. I'll come up with a new PR containing your changes.
@loechel Please the the changes in https://github.com/zopefoundation/.github/blob/master/CONTRIBUTING.md regarding CC0 contributions.

2024-02-19 07:27 UTC, closed without merging

2024-02-19 07:37 UTC, icemac commented
I created #270 as followup PR.

2024-02-19 08:22 UTC, loechel commented
@icemac how should I please or approve https://github.com/zopefoundation/.github/pull/8 if it is already merged? I am fine with it, and it makes sense for simple contributions, where people don't want to sign the contributor agreement.

2024-02-20 07:45 UTC, icemac commented
@loechel Sorry, I did not check what I wrote, I meant: "Please see the changes in …" in case you were not aware of them.