additional check for safer_getattr
zopefoundation/RestrictedPython pull request #285
Opened 2024-08-05 11:44 UTC by loechel

add an additional check for potential breakout capability via Inspection Attributes Names in the provided safer_getattr method.

2024-08-06 05:16 UTC, d-maurer approved these changes

2024-08-06 05:16 UTC, d-maurer commented on CHANGES.rst
> +  in the provided ``safer_getattr`` method that is part of the ``safer_builtins``.
There is no `safer_builtins`.
```suggestion
- Increase the safety level of ``safer_getattr``  allowing applications to use it as ``getattr`` implementation. Such use should now follow the same policy and give the same level of protection as direct attribute access in an environment based on ``RestrictedPython``'s ``safe_builtints``. 
```

2024-08-06 06:37 UTC, icemac requested changes
The mixed in reformatting of the code makes it unneccessarily hard to review this PR. Please reduce it to the actual changes needed.

2024-08-06 10:15 UTC, loechel commented
@icemac I have undone the linting changes, please review again.

2024-08-07 06:11 UTC, icemac approved these changes

2024-08-07 06:11 UTC, icemac commented on src/RestrictedPython/Guards.py
> +        )
```suggestion
            ' that is forbidden to access in RestrictedPython.')
```

2024-08-07 06:30 UTC, merged